env:
  name: "GridLife-v0"
  horizon: 512
internal_state:
  dims: ["energy","temp","integrity"]
  mu: [0.7, 0.5, 0.9]
  w:  [1.0, 0.5, 1.5]
viability:
  constraints:
    - "energy >= 0.2"
    - "temp in [0.3, 0.7]"
    - "integrity >= 0.6"
  shield:
    conf: 0.97
    horizon: 8
rewards:
  lambda_homeo: 0.7
  lambda_intr:  0.3
  intrinsic: "surprise"  # or "rnd"
train:
  algo: "SAC"        # or PPO/TD3
  batch_size: 1024
  gamma: 0.995
  update_every: 64
  model_rollouts: 5
  amortize_after_steps: 20000 # Steps before switching to amortized shield

safety_network:
  hidden_dim: 128
  lr: 0.0001

demonstrations:
  filepath: "demonstrations/expert_demonstrations.npz"